### ISSUE TITLE
Dificultad al obtener Api

### ISSUE THREAD

**Issue by ghost** [suitetecsa/suitetecsa-sdk-kotlin#6]
Hola, estaba viendo su lib que es muy buena, intenté usarla pero al agregar la implementation y sincronizarlo con mi proyecto me da error en obtenerla. El error es el siguiente: 
Could not find cu.suitetecsa:KotLibSuitETECSA:1.0-BETA.1

**Comment by lesclaz** [comment]
Muéstrame lo que hiciste.

**Comment by lesclaz** [comment]
> Agregue en mi builder.build el maven { url 'https://jitpack.io' } y en dependencies{ implementation 'cu.suitetecsa:KotLibSuitETECSA:1.0-BETA.1'
> 
> Buscando información vi recomendaciones de agregar el archivo pom.xml en la raíz del proyecto, lo hice e igual me da problemas al obtener el repositorio. :(

tienes que cambiar la implementacion a: implementation 'com.github.suitetecsa:suitetecsa-sdk-kotlin:0.1.5'
