### ISSUE TITLE
Cierre de la aplicación cuando hay campos vacios 

### ISSUE THREAD

**Issue by esalessandrxx** [suitetecsa/suitetecsa-sdk-kotlin#8]
Hola, he estado trasteando la lib, me encontré con que `client.setCredentials("user","pass"); `si no creas una comprobación de tipo `isEmpty` al acceder a la vista que contenga dicha línea de código hace que se crashee la aplicación. 
El error de salida que muestra  es:

>Caused by: cu.suitetecsa.sdk.nauta.core.exceptions.LoadInfoException: username and password are required
AndroidRuntime:at cu.suitetecsa.sdk.nauta.domain.service.NautaClient.setCredentials(NautaClient.kt:54)

No se si es normal o sea algún error que pueda ayudar en algo, o error mío al implementarlo. 

Otra cosa que no he entendido muy bien es a la hora de obtener el Captcha, si tengo que crear el método para descargarlo y mostrarlo en un `ImageView` o la propia librería se encarga de eso ya que no me queda claro de donde saldría `downloadCaptcha("captchaImage.png", client.captchaImage);` 

Saludos.

**Comment by lesclaz** [comment]
> Hola, he estado trasteando la lib, me encontré con que `client.setCredentials("user","pass"); `si no creas una comprobación de tipo `isEmpty` al acceder a la vista que contenga dicha línea de código hace que se crashee la aplicación. El error de salida que muestra es:
> 
> > Caused by: cu.suitetecsa.sdk.nauta.core.exceptions.LoadInfoException: username and password are required
> > AndroidRuntime:at cu.suitetecsa.sdk.nauta.domain.service.NautaClient.setCredentials(NautaClient.kt:54)
> 
> No se si es normal o sea algún error que pueda ayudar en algo, o error mío al implementarlo.

El error que ves lo da la propia librería, es un error programado para evitar que se intente iniciar sesión en cualquier portal sin especificar antes unas credenciales, ya que sin credenciales, no es posible iniciar sesión.

> Otra cosa que no he entendido muy bien es a la hora de obtener el Captcha, si tengo que crear el método para descargarlo y mostrarlo en un `ImageView` o la propia librería se encarga de eso ya que no me queda claro de donde saldría `downloadCaptcha("captchaImage.png", client.captchaImage);`
> 
> Saludos.

En el código de ejemplo se usa esa linea para guardar la imagen captcha en un archivo .png ya que la librería no es solo para android. cuando llamas al atributo .captchaImage, este devuelve un ByteArray que almacena el contenido de la imagen, por lo que para mostrar el captcha en un imageView debes convertir ese byteArray en un BitMap, algo asi:

```kotlin
    private fun convertImageByteArrayToBitmap(imageData: ByteArray): Bitmap {
        return BitmapFactory.decodeByteArray(imageData, 0, imageData.size)
    }
```

**Comment by lesclaz** [comment]
> Otro error que me causó fue al iniciar sesión, el error es el siguiente:
> 
> > Caused by: java.io.IOException: Cleartext HTTP traffic to [www.cubadebate.cu](http://www.cubadebate.cu) not permitted
> > at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:127)
> > at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
> > at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
> > at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:858)
> > at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:828)
> > at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:365)
> > at cu.suitetecsa.sdk.nauta.data.repository.DefaultNautaSession.get(DefaultNautaSession.kt:31)
> > at cu.suitetecsa.sdk.nauta.data.repository.NautaSession$DefaultImpls.get$default(NautaSession.kt:44)
> > at cu.suitetecsa.sdk.nauta.data.repository.JSoupNautaScrapper.isConnected(JSoupNautaScrapper.kt:171)
> > at cu.suitetecsa.sdk.nauta.data.repository.JSoupNautaScrapper.connect(JSoupNautaScrapper.kt:316)
> > at cu.suitetecsa.sdk.nauta.domain.service.NautaClient.connect(NautaClient.kt:61)
> 
> El error indica que se está realizando una solicitud HTTP al sitio web "www.cubadebate.cu" a través de una conexión no segura (HTTP en lugar de HTTPS) la solución es agregar en el Manifest `android:usesCleartextTraffic="true"` no se si en la librería también se puede hacer o de lo contrario especificar en el `README` que se necesita dicha etiqueta.
> 
> Después de eso volví a probar y se solucionó el error, pero ahora causa otro, que es:
> 
> > android.os.NetworkOnMainThreadException
> > at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1667)
> > at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
> > at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
> > at java.net.InetAddress.getAllByName(InetAddress.java:1152)
> > at com.android.okhttp.Dns$1.lookup(Dns.java:41)
> > at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
> > at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
> > at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
> > at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
> > at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
> > at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
> > at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
> > at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
> > at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
> > at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
> > at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:858)
> > at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:828)
> > at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:365)
> > at cu.suitetecsa.sdk.nauta.data.repository.DefaultNautaSession.get(DefaultNautaSession.kt:31)
> > at cu.suitetecsa.sdk.nauta.data.repository.NautaSession$DefaultImpls.get$default(NautaSession.kt:44)
> > at cu.suitetecsa.sdk.nauta.data.repository.JSoupNautaScrapper.isConnected(JSoupNautaScrapper.kt:171)
> > at cu.suitetecsa.sdk.nauta.data.repository.JSoupNautaScrapper.connect(JSoupNautaScrapper.kt:316)
> > at cu.suitetecsa.sdk.nauta.domain.service.NautaClient.connect(NautaClient.kt:61)
> 
> Quizás sea mala implementacion mía, ya me dirás, si deseas te puedo ir mandando errores que me vayan saliendo a medida que vaya progresando en la implantación de la librería.

Creo que el problema surge porque estás usando una clase aun no terminada, creo que estas intentando usar FuelNautaService y esa clase aun no la termino, deberias crear tu NautaClient de la siguiente manera:
```kotlin
val client = NautaClient(JSoupNautaScrapper(DefaultNautaSession()))
```

**Comment by esalessandrxx** [comment]
Muchas gracias bro por el soporte :) , 
voy a probar a ver que obtengo. Saludos

**Comment by lesclaz** [comment]
> Muchas gracias bro por el soporte :) , voy a probar a ver que obtengo. Saludos

Gracias a ti por colaborar, deberías actualizar la librería ya que acabo de arreglar un pequeño bug, disparaba un error cuando se iniciaba sesión en el portal de usuario con una cuenta no asociada a nauta hogar.
PD: perdón por la demora al contestar, cuando crees otro issue, puedes tirarme por telegram para enterarme antes
